import { handleCors, corsHeaders } from '../_shared/cors.ts'
import { badRequest, methodNotAllowed, internalError, unauthorized } from '../_shared/errors.ts'
import { getAdminClient } from '../_shared/adminClient.ts'
import {
  ApplicationServer,
  importVapidKeys,
  PushMessageError,
  Urgency,
} from 'jsr:@negrel/webpush@0.5.0'

// ── Web Push sender ───────────────────────────────────────────────
// Delivers browser push notifications to all active admin push
// subscriptions using VAPID-authenticated web push (RFC 8291/8292).
//
// VAPID_PUBLIC_KEY and VAPID_PRIVATE_KEY are JWK JSON strings set via
// `supabase secrets set` (generated by scripts/generate-vapid-keys.mjs).
// They are NEVER exposed to the frontend.

interface PushPayload {
  type: string
  reservation_id: string
  villa_name: string
  notification_id: string
}

interface Subscription {
  id: string
  endpoint: string
  p256dh: string
  auth: string
  admin_user_id: string
}

Deno.serve(async (req: Request) => {
  const cors = handleCors(req)
  if (cors) return cors
  if (req.method !== 'POST') return methodNotAllowed(req.method)

  try {
    const parsed = await req.json().catch(() => null)
    if (!parsed) return badRequest('Invalid JSON body')

    // Authorization: only the service role (internal Edge Function
    // invocation) may trigger push sending.
    const authHeader = req.headers.get('Authorization') ?? ''
    const token = authHeader.replace(/^Bearer\s+/i, '').trim()
    const serviceRoleKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')
    if (!token || token !== serviceRoleKey) {
      return unauthorized('Unauthorized')
    }

    const { type, reservation_id, villa_name, notification_id } =
      parsed as PushPayload

    if (!type || !reservation_id) {
      return badRequest('Missing required fields: type, reservation_id')
    }

    const vapidPublicKeyJson = Deno.env.get('VAPID_PUBLIC_KEY')
    const vapidPrivateKeyJson = Deno.env.get('VAPID_PRIVATE_KEY')

    if (!vapidPublicKeyJson || !vapidPrivateKeyJson) {
      // Push delivery is best-effort: skip silently when not configured
      return new Response(
        JSON.stringify({ sent: 0, skipped: true, reason: 'VAPID not configured' }),
        { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } },
      )
    }

    const vapidKeys = await importVapidKeys(
      {
        publicKey: JSON.parse(vapidPublicKeyJson),
        privateKey: JSON.parse(vapidPrivateKeyJson),
      },
      { extractable: false },
    )

    const appServer = await ApplicationServer.new({
      contactInformation: 'mailto:admin@kribbeverlyplace.com',
      vapidKeys,
    })

    const admin = getAdminClient()

    const { data: subscriptions, error: subError } = await admin
      .from('push_subscriptions')
      .select('id, endpoint, p256dh, auth, admin_user_id')
      .eq('is_active', true)

    if (subError) throw subError
    if (!subscriptions || subscriptions.length === 0) {
      return new Response(
        JSON.stringify({ sent: 0, reason: 'No active subscriptions' }),
        { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } },
      )
    }

    const pushPayload: Record<string, string> = {
      type,
      notification_id: notification_id || '',
      reservation_id,
      title: 'New Reservation',
      body: `A new reservation has been submitted for ${villa_name}.`,
      url: '/admin/reservations',
      tag: `reservation-${reservation_id}`,
    }

    let sent = 0
    let failed = 0
    const invalidEndpoints: string[] = []

    await Promise.allSettled(
      (subscriptions as Subscription[]).map(async (sub) => {
        try {
          const subscriber = appServer.subscribe({
            endpoint: sub.endpoint,
            keys: { p256dh: sub.p256dh, auth: sub.auth },
          })
          await subscriber.pushTextMessage(JSON.stringify(pushPayload), {
            urgency: Urgency.High,
            ttl: 86400,
          })
          sent++
        } catch (err) {
          if (err instanceof PushMessageError && err.response.status >= 400) {
            const status = err.response.status
            if (status === 404 || status === 410) {
              invalidEndpoints.push(sub.endpoint)
            }
          }
          failed++
        }
      }),
    )

    if (invalidEndpoints.length > 0) {
      await admin
        .from('push_subscriptions')
        .update({ is_active: false })
        .in('endpoint', invalidEndpoints)
    }

    return new Response(
      JSON.stringify({ sent, failed, deactivated: invalidEndpoints.length }),
      { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } },
    )
  } catch (err) {
    return internalError(err)
  }
})
